version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
  frontend:
    build:
      context: ./npi-calculator
      dockerfile: Dockerfile
    ports:
      - '3000:80'
